// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

import "encoding/json"
import "fmt"
import "reflect"

// Plant Labeling System very well-established in Germany which helps locating a
// device in a plant based on its function in the plant. The acronym originates
// from the German word "Anlagekennzeichnung" (something like "plant coding
// system").
type Akz struct {
	// Type designator that provides support for polymorphism using location.
	LocationType *AkzLocationType `json:"location_type,omitempty" yaml:"location_type,omitempty" mapstructure:"location_type,omitempty"`

	// String that provides the location of the device in the plant. This string is
	// built-up concatenating different information items with separators. Some of
	// these systems are standardized, some others are company-specific.
	PlantDesignation string `json:"plant_designation" yaml:"plant_designation" mapstructure:"plant_designation"`
}

type AkzLocationType string

const AkzLocationTypeAkz AkzLocationType = "Akz"

var enumValues_AkzLocationType = []interface{}{
	"Akz",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AkzLocationType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AkzLocationType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AkzLocationType, v)
	}
	*j = AkzLocationType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Akz) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["plant_designation"]; raw != nil && !ok {
		return fmt.Errorf("field plant_designation in Akz: required")
	}
	type Plain Akz
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Akz(plain)
	return nil
}

// An asset is the representation of a functional object with a technical function
// that is known to Industrial Asset Hub (IAH). Industrial Asset Hub (IAH) might
// want to manage the asset, model its relationships with other assets, or it might
// know the asset and ignore it,...
// An asset instance might represent a physical object (like a Raspberry Pi or an
// application running on a system) or a virtual object (like a router in a network
// topology, no matter which physical device it is). In both cases an identifier
// for the object being represented is needed.
type Asset struct {
	// An asset identifier is an asset attribute that provides enough information to
	// unequivocally identify the represented object.
	// In some cases the ID attribute acts simultaneously as a reference for the asset
	// instance and as identifier for the represented object. Otherwise at least one
	// asset identifier is needed.
	// There can be multiple asset_identifiers with different goals. For example, the
	// information of a metal nameplate can be used by a human-being to identify a
	// device represented by an asset instance, but a software certificate provided by
	// a device might help a software component identify the device in the network,...
	// An asset identifier might have an identifier_type, that defines its format and
	// possibly even semantics.
	AssetIdentifiers []interface{} `json:"asset_identifiers" yaml:"asset_identifiers" mapstructure:"asset_identifiers"`

	// List of device management operations supported by an asset. Each operation type
	// might appear only once.
	AssetOperations []AssetOperation `json:"asset_operations,omitempty" yaml:"asset_operations,omitempty" mapstructure:"asset_operations,omitempty"`

	// An asset might have a connection point that can be used to connect with the
	// asset. In the case of devices, at least one connection point is required. It
	// might be a connection point needed for AssetManagement for interaction with the
	// asset, or for other connections of the asset related to the asset function but
	// not to device management.
	ConnectionPoints []interface{} `json:"connection_points,omitempty" yaml:"connection_points,omitempty" mapstructure:"connection_points,omitempty"`

	// A textual description of the item's purpose and use.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// URL of the schema that defines the functional object type.
	FunctionalObjectSchemaUrl string `json:"functional_object_schema_url" yaml:"functional_object_schema_url" mapstructure:"functional_object_schema_url"`

	// Type designator that supports polymorphism using functional parts. This type is
	// used for validation of the provided functional objects.
	FunctionalObjectType AssetFunctionalObjectType `json:"functional_object_type" yaml:"functional_object_type" mapstructure:"functional_object_type"`

	// Metadata associated with an object.
	InstanceAnnotations []InstanceAnnotation `json:"instance_annotations,omitempty" yaml:"instance_annotations,omitempty" mapstructure:"instance_annotations,omitempty"`

	// Possible ways to know where an asset is located.
	Location []interface{} `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// The name of the item.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The current operating mode of the asset.
	OperatingMode interface{} `json:"operating_mode,omitempty" yaml:"operating_mode,omitempty" mapstructure:"operating_mode,omitempty"`

	// Information about the product instance.
	ProductInstanceInformation interface{} `json:"product_instance_information,omitempty" yaml:"product_instance_information,omitempty" mapstructure:"product_instance_information,omitempty"`

	// An asset can host software artifacts that might want to be tracked. This can be
	// used simply to keep track of the firmware version or to keep a full-blown
	// Software Bill of Material (SBOM).
	SoftwareComponents []interface{} `json:"software_components,omitempty" yaml:"software_components,omitempty" mapstructure:"software_components,omitempty"`
}

type AssetFunctionalObjectType string

const AssetFunctionalObjectTypeAsset AssetFunctionalObjectType = "Asset"

var enumValues_AssetFunctionalObjectType = []interface{}{
	"Asset",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AssetFunctionalObjectType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AssetFunctionalObjectType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AssetFunctionalObjectType, v)
	}
	*j = AssetFunctionalObjectType(v)
	return nil
}

// Asset Link that can be used to interact with assets and can be reached by the
// gateway.
type AssetLink struct {
	// Reference to the software artifact asset.
	// As of now the combination of multiple software artifacts into a running
	// software (for example with plug-ins) is not supported and cannot be natively
	// modeled.
	Artifact interface{} `json:"artifact,omitempty" yaml:"artifact,omitempty" mapstructure:"artifact,omitempty"`
}

// Attributes that help locate where an asset can be physically found.
type AssetLocation struct {
	// Type designator that provides support for polymorphism using location.
	LocationType *AssetLocationLocationType `json:"location_type,omitempty" yaml:"location_type,omitempty" mapstructure:"location_type,omitempty"`
}

type AssetLocationLocationType string

const AssetLocationLocationTypeAssetLocation AssetLocationLocationType = "AssetLocation"

var enumValues_AssetLocationLocationType = []interface{}{
	"AssetLocation",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AssetLocationLocationType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AssetLocationLocationType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AssetLocationLocationType, v)
	}
	*j = AssetLocationLocationType(v)
	return nil
}

// Operations that can be performed on the asset
type AssetOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AssetOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in AssetOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in AssetOperation: required")
	}
	type Plain AssetOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AssetOperation(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Asset) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifiers"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifiers in Asset: required")
	}
	if _, ok := raw["functional_object_schema_url"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_schema_url in Asset: required")
	}
	if _, ok := raw["functional_object_type"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_type in Asset: required")
	}
	type Plain Asset
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Asset(plain)
	return nil
}

// Backup operation can be performed on the asset
type BackupOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BackupOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in BackupOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in BackupOperation: required")
	}
	type Plain BackupOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = BackupOperation(plain)
	return nil
}

type CdmBaseSchemaV190Json map[string]interface{}

// Base64 encoded version of certificate subject key identifier will be the
// identifier.
type CertificateIdentifier struct {
	// Type designator that supports polymorphism using asset identifiers.
	AssetIdentifierType CertificateIdentifierAssetIdentifierType `json:"asset_identifier_type" yaml:"asset_identifier_type" mapstructure:"asset_identifier_type"`

	// Base64 encoded version of certificate subject key identifier
	CertificateId string `json:"certificate_id" yaml:"certificate_id" mapstructure:"certificate_id"`

	// Type of an items identifier.
	IdentifierType *string `json:"identifier_type,omitempty" yaml:"identifier_type,omitempty" mapstructure:"identifier_type,omitempty"`

	// Number that indicates how uncertain an identifier is compared to other
	// identifiers provided by an Asset Link. The higher the number, the more
	// uncertain the identification must be considered. This number must be considered
	// relative to the other identifiers for the same element. The default value is 0,
	// meaning no uncertainty.
	// This index helps to decide which identifiers are better suited for
	// deduplication across Asset Links. The identifier provided by two different
	// Asset Links with the lowest uncertainty should be chosen for deduplication
	// purposes.
	IdentifierUncertainty *int `json:"identifier_uncertainty,omitempty" yaml:"identifier_uncertainty,omitempty" mapstructure:"identifier_uncertainty,omitempty"`
}

type CertificateIdentifierAssetIdentifierType string

const CertificateIdentifierAssetIdentifierTypeCertificateIdentifier CertificateIdentifierAssetIdentifierType = "CertificateIdentifier"

var enumValues_CertificateIdentifierAssetIdentifierType = []interface{}{
	"CertificateIdentifier",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CertificateIdentifierAssetIdentifierType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CertificateIdentifierAssetIdentifierType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CertificateIdentifierAssetIdentifierType, v)
	}
	*j = CertificateIdentifierAssetIdentifierType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CertificateIdentifier) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifier_type"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifier_type in CertificateIdentifier: required")
	}
	if _, ok := raw["certificate_id"]; raw != nil && !ok {
		return fmt.Errorf("field certificate_id in CertificateIdentifier: required")
	}
	type Plain CertificateIdentifier
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CertificateIdentifier(plain)
	return nil
}

// Change mode operation can be performed on the asset
type ChangeModeOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChangeModeOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in ChangeModeOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in ChangeModeOperation: required")
	}
	type Plain ChangeModeOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ChangeModeOperation(plain)
	return nil
}

// Asset is in CIR (Configuration In Run) mode.
type CirOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CirOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in CirOperatingMode: required")
	}
	type Plain CirOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CirOperatingMode(plain)
	return nil
}

// Identifier especially for assets that are imported from external sources and do
// not provide a native identifier. The 'name' is used to specify the external
// source or type of the identifier. The 'value' is used to provide the actual
// identifier value within that context.
type CustomIdentifier struct {
	// Type designator that supports polymorphism using asset identifiers.
	AssetIdentifierType CustomIdentifierAssetIdentifierType `json:"asset_identifier_type" yaml:"asset_identifier_type" mapstructure:"asset_identifier_type"`

	// Type of an items identifier.
	IdentifierType *string `json:"identifier_type,omitempty" yaml:"identifier_type,omitempty" mapstructure:"identifier_type,omitempty"`

	// Number that indicates how uncertain an identifier is compared to other
	// identifiers provided by an Asset Link. The higher the number, the more
	// uncertain the identification must be considered. This number must be considered
	// relative to the other identifiers for the same element. The default value is 0,
	// meaning no uncertainty.
	// This index helps to decide which identifiers are better suited for
	// deduplication across Asset Links. The identifier provided by two different
	// Asset Links with the lowest uncertainty should be chosen for deduplication
	// purposes.
	IdentifierUncertainty *int `json:"identifier_uncertainty,omitempty" yaml:"identifier_uncertainty,omitempty" mapstructure:"identifier_uncertainty,omitempty"`

	// The name of the item.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The value of the custom identifier.
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type CustomIdentifierAssetIdentifierType string

const CustomIdentifierAssetIdentifierTypeCustomIdentifier CustomIdentifierAssetIdentifierType = "CustomIdentifier"

var enumValues_CustomIdentifierAssetIdentifierType = []interface{}{
	"CustomIdentifier",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomIdentifierAssetIdentifierType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CustomIdentifierAssetIdentifierType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CustomIdentifierAssetIdentifierType, v)
	}
	*j = CustomIdentifierAssetIdentifierType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomIdentifier) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifier_type"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifier_type in CustomIdentifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in CustomIdentifier: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in CustomIdentifier: required")
	}
	type Plain CustomIdentifier
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomIdentifier(plain)
	return nil
}

// Asset is defective.
type DefectiveOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DefectiveOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in DefectiveOperatingMode: required")
	}
	type Plain DefectiveOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = DefectiveOperatingMode(plain)
	return nil
}

// A device is a special type of asset that can be managed with some asset
// management system. In order to be manageable, it requires at least one
// connection point for the asset management to communicate with the device and
// software capable of interacting with the asset management.
type Device struct {
	// An asset identifier is an asset attribute that provides enough information to
	// unequivocally identify the represented object.
	// In some cases the ID attribute acts simultaneously as a reference for the asset
	// instance and as identifier for the represented object. Otherwise at least one
	// asset identifier is needed.
	// There can be multiple asset_identifiers with different goals. For example, the
	// information of a metal nameplate can be used by a human-being to identify a
	// device represented by an asset instance, but a software certificate provided by
	// a device might help a software component identify the device in the network,...
	// An asset identifier might have an identifier_type, that defines its format and
	// possibly even semantics.
	AssetIdentifiers []interface{} `json:"asset_identifiers" yaml:"asset_identifiers" mapstructure:"asset_identifiers"`

	// List of device management operations supported by an asset. Each operation type
	// might appear only once.
	AssetOperations []AssetOperation `json:"asset_operations,omitempty" yaml:"asset_operations,omitempty" mapstructure:"asset_operations,omitempty"`

	// An asset might have a connection point that can be used to connect with the
	// asset. In the case of devices, at least one connection point is required. It
	// might be a connection point needed for AssetManagement for interaction with the
	// asset, or for other connections of the asset related to the asset function but
	// not to device management.
	ConnectionPoints []interface{} `json:"connection_points,omitempty" yaml:"connection_points,omitempty" mapstructure:"connection_points,omitempty"`

	// A textual description of the item's purpose and use.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// URL of the schema that defines the functional object type.
	FunctionalObjectSchemaUrl string `json:"functional_object_schema_url" yaml:"functional_object_schema_url" mapstructure:"functional_object_schema_url"`

	// Type designator that supports polymorphism using functional parts. This type is
	// used for validation of the provided functional objects.
	FunctionalObjectType DeviceFunctionalObjectType `json:"functional_object_type" yaml:"functional_object_type" mapstructure:"functional_object_type"`

	// Metadata associated with an object.
	InstanceAnnotations []InstanceAnnotation `json:"instance_annotations,omitempty" yaml:"instance_annotations,omitempty" mapstructure:"instance_annotations,omitempty"`

	// Possible ways to know where an asset is located.
	Location []interface{} `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// The name of the item.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The current operating mode of the asset.
	OperatingMode interface{} `json:"operating_mode,omitempty" yaml:"operating_mode,omitempty" mapstructure:"operating_mode,omitempty"`

	// Information about the product instance.
	ProductInstanceInformation interface{} `json:"product_instance_information,omitempty" yaml:"product_instance_information,omitempty" mapstructure:"product_instance_information,omitempty"`

	// An asset can host software artifacts that might want to be tracked. This can be
	// used simply to keep track of the firmware version or to keep a full-blown
	// Software Bill of Material (SBOM).
	SoftwareComponents []interface{} `json:"software_components,omitempty" yaml:"software_components,omitempty" mapstructure:"software_components,omitempty"`
}

type DeviceFunctionalObjectType string

const DeviceFunctionalObjectTypeDevice DeviceFunctionalObjectType = "Device"

var enumValues_DeviceFunctionalObjectType = []interface{}{
	"Device",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeviceFunctionalObjectType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DeviceFunctionalObjectType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DeviceFunctionalObjectType, v)
	}
	*j = DeviceFunctionalObjectType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Device) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifiers"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifiers in Device: required")
	}
	if _, ok := raw["functional_object_schema_url"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_schema_url in Device: required")
	}
	if _, ok := raw["functional_object_type"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_type in Device: required")
	}
	type Plain Device
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Device(plain)
	return nil
}

// Asset is in error search mode.
type ErrorSearchOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorSearchOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in ErrorSearchOperatingMode: required")
	}
	type Plain ErrorSearchOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ErrorSearchOperatingMode(plain)
	return nil
}

// A hardware ConnectionPoint that supports one of the Ethernet networking
// protocols as defined in the standard [IEEE
// 802.3](https://en.wikipedia.org/wiki/IEEE_802.3).
type EthernetPort struct {
	// Type designator that provides support for polymorphism using connection points.
	ConnectionPointType EthernetPortConnectionPointType `json:"connection_point_type" yaml:"connection_point_type" mapstructure:"connection_point_type"`

	// The identifier is used to identify the connection point within the asset. It
	// shall be generated by the asset link. Setting this identifier is only needed if
	// the connection point needs to be referenced by an other connection point as
	// RelatedConnectionPoint.
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// The MAC address of the port. It is expected to be fixed, but in some ethernet
	// ports it can be changed.
	// An asset instance must provide for each ethernet port the default MAC address.
	MacAddress string `json:"mac_address" yaml:"mac_address" mapstructure:"mac_address"`

	// Name of the connection point. The name is provided by the Asset Link during the
	// discovery process. Usually, the name is provided by the operating system of the
	// asset or may be labeled on the asset itself.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// A connection point might rely on another connection point to work.
	// Examples: a TCP/IP connection can only work if there is some kind of connection
	// point at physical level (e.g. Ethernet Port, Bluetooth Port), a container might
	// be connected over a virtual ethernet to a software bridge, a software bridge
	// might be directly connected to an ethernet port.
	// This attribute enables modeling these kind of dependencies in a limited way.
	// Other modeling mechanisms might be needed to model complex networking setups.
	RelatedConnectionPoints []RelatedConnectionPoint `json:"related_connection_points,omitempty" yaml:"related_connection_points,omitempty" mapstructure:"related_connection_points,omitempty"`
}

type EthernetPortConnectionPointType string

const EthernetPortConnectionPointTypeEthernetPort EthernetPortConnectionPointType = "EthernetPort"

var enumValues_EthernetPortConnectionPointType = []interface{}{
	"EthernetPort",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EthernetPortConnectionPointType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EthernetPortConnectionPointType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EthernetPortConnectionPointType, v)
	}
	*j = EthernetPortConnectionPointType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EthernetPort) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["connection_point_type"]; raw != nil && !ok {
		return fmt.Errorf("field connection_point_type in EthernetPort: required")
	}
	if _, ok := raw["mac_address"]; raw != nil && !ok {
		return fmt.Errorf("field mac_address in EthernetPort: required")
	}
	type Plain EthernetPort
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = EthernetPort(plain)
	return nil
}

// Factory reset operation can be performed on the asset
type FactoryResetOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FactoryResetOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in FactoryResetOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in FactoryResetOperation: required")
	}
	type Plain FactoryResetOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = FactoryResetOperation(plain)
	return nil
}

// Firmware update operation can be performed on the asset
type FirmwareUpdateOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FirmwareUpdateOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in FirmwareUpdateOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in FirmwareUpdateOperation: required")
	}
	type Plain FirmwareUpdateOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = FirmwareUpdateOperation(plain)
	return nil
}

// Gateway as a software asset can be mapped using the class. It represents the
// container bundle that is deployed on a device or virtual machine and provides
// connectivity between assets in the shopfloor and the IAH backend.
type Gateway struct {
	// An asset identifier is an asset attribute that provides enough information to
	// unequivocally identify the represented object.
	// In some cases the ID attribute acts simultaneously as a reference for the asset
	// instance and as identifier for the represented object. Otherwise at least one
	// asset identifier is needed.
	// There can be multiple asset_identifiers with different goals. For example, the
	// information of a metal nameplate can be used by a human-being to identify a
	// device represented by an asset instance, but a software certificate provided by
	// a device might help a software component identify the device in the network,...
	// An asset identifier might have an identifier_type, that defines its format and
	// possibly even semantics.
	AssetIdentifiers []interface{} `json:"asset_identifiers" yaml:"asset_identifiers" mapstructure:"asset_identifiers"`

	// List of asset links that are connected to the asset gateway.
	AssetLinks []AssetLink `json:"asset_links,omitempty" yaml:"asset_links,omitempty" mapstructure:"asset_links,omitempty"`

	// List of device management operations supported by an asset. Each operation type
	// might appear only once.
	AssetOperations []AssetOperation `json:"asset_operations,omitempty" yaml:"asset_operations,omitempty" mapstructure:"asset_operations,omitempty"`

	// An asset might have a connection point that can be used to connect with the
	// asset. In the case of devices, at least one connection point is required. It
	// might be a connection point needed for AssetManagement for interaction with the
	// asset, or for other connections of the asset related to the asset function but
	// not to device management.
	ConnectionPoints []interface{} `json:"connection_points,omitempty" yaml:"connection_points,omitempty" mapstructure:"connection_points,omitempty"`

	// A textual description of the item's purpose and use.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// URL of the schema that defines the functional object type.
	FunctionalObjectSchemaUrl string `json:"functional_object_schema_url" yaml:"functional_object_schema_url" mapstructure:"functional_object_schema_url"`

	// Type designator that supports polymorphism using functional parts. This type is
	// used for validation of the provided functional objects.
	FunctionalObjectType GatewayFunctionalObjectType `json:"functional_object_type" yaml:"functional_object_type" mapstructure:"functional_object_type"`

	// Metadata associated with an object.
	InstanceAnnotations []InstanceAnnotation `json:"instance_annotations,omitempty" yaml:"instance_annotations,omitempty" mapstructure:"instance_annotations,omitempty"`

	// Possible ways to know where an asset is located.
	Location []interface{} `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// The name of the item.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The current operating mode of the asset.
	OperatingMode interface{} `json:"operating_mode,omitempty" yaml:"operating_mode,omitempty" mapstructure:"operating_mode,omitempty"`

	// Information about the product instance.
	ProductInstanceInformation interface{} `json:"product_instance_information,omitempty" yaml:"product_instance_information,omitempty" mapstructure:"product_instance_information,omitempty"`

	// An asset can host software artifacts that might want to be tracked. This can be
	// used simply to keep track of the firmware version or to keep a full-blown
	// Software Bill of Material (SBOM).
	SoftwareComponents []interface{} `json:"software_components,omitempty" yaml:"software_components,omitempty" mapstructure:"software_components,omitempty"`
}

type GatewayFunctionalObjectType string

const GatewayFunctionalObjectTypeGateway GatewayFunctionalObjectType = "Gateway"

var enumValues_GatewayFunctionalObjectType = []interface{}{
	"Gateway",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GatewayFunctionalObjectType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GatewayFunctionalObjectType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GatewayFunctionalObjectType, v)
	}
	*j = GatewayFunctionalObjectType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Gateway) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifiers"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifiers in Gateway: required")
	}
	if _, ok := raw["functional_object_schema_url"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_schema_url in Gateway: required")
	}
	if _, ok := raw["functional_object_type"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_type in Gateway: required")
	}
	type Plain Gateway
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Gateway(plain)
	return nil
}

// Geographic coordinates in which an asset can be found.
type GeoLocation struct {
	// The elevation of a location in meters (WGS 84).
	Elevation *float64 `json:"elevation,omitempty" yaml:"elevation,omitempty" mapstructure:"elevation,omitempty"`

	// The latitude of a location. For example 37.42242 (WGS 84).
	Latitude *float64 `json:"latitude,omitempty" yaml:"latitude,omitempty" mapstructure:"latitude,omitempty"`

	// Type designator that provides support for polymorphism using location.
	LocationType *GeoLocationLocationType `json:"location_type,omitempty" yaml:"location_type,omitempty" mapstructure:"location_type,omitempty"`

	// The longitude of a location. For example -122.08585 (WGS 84).
	Longitude *float64 `json:"longitude,omitempty" yaml:"longitude,omitempty" mapstructure:"longitude,omitempty"`
}

type GeoLocationLocationType string

const GeoLocationLocationTypeGeoLocation GeoLocationLocationType = "GeoLocation"

var enumValues_GeoLocationLocationType = []interface{}{
	"GeoLocation",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GeoLocationLocationType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GeoLocationLocationType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GeoLocationLocationType, v)
	}
	*j = GeoLocationLocationType(v)
	return nil
}

// Asset is halted.
type HaltOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HaltOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in HaltOperatingMode: required")
	}
	type Plain HaltOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = HaltOperatingMode(plain)
	return nil
}

// Identifier for an asset instance using a vendor-provided ID Link URL. The URL
// must be absolute (i.e. include a scheme and host) and follow the ID Link
// convention (IEC 61406 / DIN SPEC 91406).
type IdLinkIdentifier struct {
	// Type designator that supports polymorphism using asset identifiers.
	AssetIdentifierType IdLinkIdentifierAssetIdentifierType `json:"asset_identifier_type" yaml:"asset_identifier_type" mapstructure:"asset_identifier_type"`

	// A vendor-supplied URL that uniquely identifies a product instance following the
	// ID Link convention (IEC 61406 / DIN SPEC 91406). The URL must be absolute (i.e.
	// include a scheme and host). For comparison and deduplication purposes, the
	// scheme and host are case-insensitive, while path and query are treated as
	// case-sensitive.
	IdLink string `json:"id_link" yaml:"id_link" mapstructure:"id_link"`

	// Type of an items identifier.
	IdentifierType *string `json:"identifier_type,omitempty" yaml:"identifier_type,omitempty" mapstructure:"identifier_type,omitempty"`

	// Number that indicates how uncertain an identifier is compared to other
	// identifiers provided by an Asset Link. The higher the number, the more
	// uncertain the identification must be considered. This number must be considered
	// relative to the other identifiers for the same element. The default value is 0,
	// meaning no uncertainty.
	// This index helps to decide which identifiers are better suited for
	// deduplication across Asset Links. The identifier provided by two different
	// Asset Links with the lowest uncertainty should be chosen for deduplication
	// purposes.
	IdentifierUncertainty *int `json:"identifier_uncertainty,omitempty" yaml:"identifier_uncertainty,omitempty" mapstructure:"identifier_uncertainty,omitempty"`
}

type IdLinkIdentifierAssetIdentifierType string

const IdLinkIdentifierAssetIdentifierTypeIdLinkIdentifier IdLinkIdentifierAssetIdentifierType = "IdLinkIdentifier"

var enumValues_IdLinkIdentifierAssetIdentifierType = []interface{}{
	"IdLinkIdentifier",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IdLinkIdentifierAssetIdentifierType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IdLinkIdentifierAssetIdentifierType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IdLinkIdentifierAssetIdentifierType, v)
	}
	*j = IdLinkIdentifierAssetIdentifierType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IdLinkIdentifier) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifier_type"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifier_type in IdLinkIdentifier: required")
	}
	if _, ok := raw["id_link"]; raw != nil && !ok {
		return fmt.Errorf("field id_link in IdLinkIdentifier: required")
	}
	type Plain IdLinkIdentifier
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = IdLinkIdentifier(plain)
	return nil
}

// Key/value pair that can be used to add metadata to an object.
type InstanceAnnotation struct {
	// The identifier of a key/value pair.
	Key *string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// The real metadata of a key/value pair.
	Value *string `json:"value,omitempty" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

// Configuration of an IP port. Please note that the configuration of an IP address
// is independent of the Ethernet port configuration.
type Ipv4Connectivity struct {
	// Type designator that provides support for polymorphism using connection points.
	ConnectionPointType Ipv4ConnectivityConnectionPointType `json:"connection_point_type" yaml:"connection_point_type" mapstructure:"connection_point_type"`

	// The identifier is used to identify the connection point within the asset. It
	// shall be generated by the asset link. Setting this identifier is only needed if
	// the connection point needs to be referenced by an other connection point as
	// RelatedConnectionPoint.
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// The IP v4 address of a device port.
	Ipv4Address string `json:"ipv4_address" yaml:"ipv4_address" mapstructure:"ipv4_address"`

	// Name of the connection point. The name is provided by the Asset Link during the
	// discovery process. Usually, the name is provided by the operating system of the
	// asset or may be labeled on the asset itself.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The mask that segregates IPs v4 belonging to the same sub-network from the
	// rest.
	NetworkMask *string `json:"network_mask,omitempty" yaml:"network_mask,omitempty" mapstructure:"network_mask,omitempty"`

	// A connection point might rely on another connection point to work.
	// Examples: a TCP/IP connection can only work if there is some kind of connection
	// point at physical level (e.g. Ethernet Port, Bluetooth Port), a container might
	// be connected over a virtual ethernet to a software bridge, a software bridge
	// might be directly connected to an ethernet port.
	// This attribute enables modeling these kind of dependencies in a limited way.
	// Other modeling mechanisms might be needed to model complex networking setups.
	RelatedConnectionPoints []RelatedConnectionPoint `json:"related_connection_points,omitempty" yaml:"related_connection_points,omitempty" mapstructure:"related_connection_points,omitempty"`

	// The IPv4 address of the router (AKA gateway) corresponding to a IPv4 address.
	RouterIpv4Address *string `json:"router_ipv4_address,omitempty" yaml:"router_ipv4_address,omitempty" mapstructure:"router_ipv4_address,omitempty"`
}

type Ipv4ConnectivityConnectionPointType string

const Ipv4ConnectivityConnectionPointTypeIpv4Connectivity Ipv4ConnectivityConnectionPointType = "Ipv4Connectivity"

var enumValues_Ipv4ConnectivityConnectionPointType = []interface{}{
	"Ipv4Connectivity",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Ipv4ConnectivityConnectionPointType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Ipv4ConnectivityConnectionPointType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Ipv4ConnectivityConnectionPointType, v)
	}
	*j = Ipv4ConnectivityConnectionPointType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Ipv4Connectivity) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["connection_point_type"]; raw != nil && !ok {
		return fmt.Errorf("field connection_point_type in Ipv4Connectivity: required")
	}
	if _, ok := raw["ipv4_address"]; raw != nil && !ok {
		return fmt.Errorf("field ipv4_address in Ipv4Connectivity: required")
	}
	type Plain Ipv4Connectivity
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Ipv4Connectivity(plain)
	return nil
}

// Configuration of an IP port. Please note that the configuration of an IP address
// is independent of the Ethernet port configuration.
type Ipv6Connectivity struct {
	// Type designator that provides support for polymorphism using connection points.
	ConnectionPointType Ipv6ConnectivityConnectionPointType `json:"connection_point_type" yaml:"connection_point_type" mapstructure:"connection_point_type"`

	// The identifier is used to identify the connection point within the asset. It
	// shall be generated by the asset link. Setting this identifier is only needed if
	// the connection point needs to be referenced by an other connection point as
	// RelatedConnectionPoint.
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// The IP v6 address of a device port.
	Ipv6Address string `json:"ipv6_address" yaml:"ipv6_address" mapstructure:"ipv6_address"`

	// Prefix of the subnetwork in which the IP address is located.
	Ipv6NetworkPrefix *string `json:"ipv6_network_prefix,omitempty" yaml:"ipv6_network_prefix,omitempty" mapstructure:"ipv6_network_prefix,omitempty"`

	// Name of the connection point. The name is provided by the Asset Link during the
	// discovery process. Usually, the name is provided by the operating system of the
	// asset or may be labeled on the asset itself.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// A connection point might rely on another connection point to work.
	// Examples: a TCP/IP connection can only work if there is some kind of connection
	// point at physical level (e.g. Ethernet Port, Bluetooth Port), a container might
	// be connected over a virtual ethernet to a software bridge, a software bridge
	// might be directly connected to an ethernet port.
	// This attribute enables modeling these kind of dependencies in a limited way.
	// Other modeling mechanisms might be needed to model complex networking setups.
	RelatedConnectionPoints []RelatedConnectionPoint `json:"related_connection_points,omitempty" yaml:"related_connection_points,omitempty" mapstructure:"related_connection_points,omitempty"`

	// The IP v6 address of the default IP v6 router (AKA gateway).
	RouterIpv6Address *string `json:"router_ipv6_address,omitempty" yaml:"router_ipv6_address,omitempty" mapstructure:"router_ipv6_address,omitempty"`
}

type Ipv6ConnectivityConnectionPointType string

const Ipv6ConnectivityConnectionPointTypeIpv6Connectivity Ipv6ConnectivityConnectionPointType = "Ipv6Connectivity"

var enumValues_Ipv6ConnectivityConnectionPointType = []interface{}{
	"Ipv6Connectivity",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Ipv6ConnectivityConnectionPointType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Ipv6ConnectivityConnectionPointType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Ipv6ConnectivityConnectionPointType, v)
	}
	*j = Ipv6ConnectivityConnectionPointType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Ipv6Connectivity) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["connection_point_type"]; raw != nil && !ok {
		return fmt.Errorf("field connection_point_type in Ipv6Connectivity: required")
	}
	if _, ok := raw["ipv6_address"]; raw != nil && !ok {
		return fmt.Errorf("field ipv6_address in Ipv6Connectivity: required")
	}
	type Plain Ipv6Connectivity
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Ipv6Connectivity(plain)
	return nil
}

// Asset has an active network link.
type LinkUpOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LinkUpOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in LinkUpOperatingMode: required")
	}
	type Plain LinkUpOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LinkUpOperatingMode(plain)
	return nil
}

// Identifier for an Asset instance using the mac address.
type MacIdentifier struct {
	// Type designator that supports polymorphism using asset identifiers.
	AssetIdentifierType MacIdentifierAssetIdentifierType `json:"asset_identifier_type" yaml:"asset_identifier_type" mapstructure:"asset_identifier_type"`

	// Type of an items identifier.
	IdentifierType *string `json:"identifier_type,omitempty" yaml:"identifier_type,omitempty" mapstructure:"identifier_type,omitempty"`

	// Number that indicates how uncertain an identifier is compared to other
	// identifiers provided by an Asset Link. The higher the number, the more
	// uncertain the identification must be considered. This number must be considered
	// relative to the other identifiers for the same element. The default value is 0,
	// meaning no uncertainty.
	// This index helps to decide which identifiers are better suited for
	// deduplication across Asset Links. The identifier provided by two different
	// Asset Links with the lowest uncertainty should be chosen for deduplication
	// purposes.
	IdentifierUncertainty *int `json:"identifier_uncertainty,omitempty" yaml:"identifier_uncertainty,omitempty" mapstructure:"identifier_uncertainty,omitempty"`

	// The MAC address of the port. It is expected to be fixed, but in some ethernet
	// ports it can be changed.
	// An asset instance must provide for each ethernet port the default MAC address.
	MacAddress string `json:"mac_address" yaml:"mac_address" mapstructure:"mac_address"`
}

type MacIdentifierAssetIdentifierType string

const MacIdentifierAssetIdentifierTypeMacIdentifier MacIdentifierAssetIdentifierType = "MacIdentifier"

var enumValues_MacIdentifierAssetIdentifierType = []interface{}{
	"MacIdentifier",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MacIdentifierAssetIdentifierType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MacIdentifierAssetIdentifierType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MacIdentifierAssetIdentifierType, v)
	}
	*j = MacIdentifierAssetIdentifierType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MacIdentifier) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifier_type"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifier_type in MacIdentifier: required")
	}
	if _, ok := raw["mac_address"]; raw != nil && !ok {
		return fmt.Errorf("field mac_address in MacIdentifier: required")
	}
	type Plain MacIdentifier
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MacIdentifier(plain)
	return nil
}

// Memory reset operation can be performed on the asset
type MemoryResetOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MemoryResetOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in MemoryResetOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in MemoryResetOperation: required")
	}
	type Plain MemoryResetOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MemoryResetOperation(plain)
	return nil
}

// Representation of the location of an asset in an automation environment, where
// the information about the place where the device is mounted is used.
type MountingLocation struct {
	// Type designator that provides support for polymorphism using location.
	LocationType *MountingLocationLocationType `json:"location_type,omitempty" yaml:"location_type,omitempty" mapstructure:"location_type,omitempty"`

	// User-assigned name of the slot, within the specified rack, where the asset can
	// be found.
	SlotName *string `json:"slot_name,omitempty" yaml:"slot_name,omitempty" mapstructure:"slot_name,omitempty"`

	// Identification of the slot, within the specified rack, where the asset can be
	// found.
	SlotNumber *int `json:"slot_number,omitempty" yaml:"slot_number,omitempty" mapstructure:"slot_number,omitempty"`

	// Identification of the rack where the asset can be found.
	StationNumber *int `json:"station_number,omitempty" yaml:"station_number,omitempty" mapstructure:"station_number,omitempty"`

	// Identification of the subslot, within the specified slot, where the asset can
	// be found.
	SubslotNumber *int `json:"subslot_number,omitempty" yaml:"subslot_number,omitempty" mapstructure:"subslot_number,omitempty"`
}

type MountingLocationLocationType string

const MountingLocationLocationTypeMountingLocation MountingLocationLocationType = "MountingLocation"

var enumValues_MountingLocationLocationType = []interface{}{
	"MountingLocation",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MountingLocationLocationType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MountingLocationLocationType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MountingLocationLocationType, v)
	}
	*j = MountingLocationLocationType(v)
	return nil
}

// Asset has no power.
type NoPowerOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoPowerOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in NoPowerOperatingMode: required")
	}
	type Plain NoPowerOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NoPowerOperatingMode(plain)
	return nil
}

// Asset is in a not supported operating mode.
type NotSupportedOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NotSupportedOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in NotSupportedOperatingMode: required")
	}
	type Plain NotSupportedOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NotSupportedOperatingMode(plain)
	return nil
}

// Plant Labeling System that is well-established in Germany and helps locate a
// device in a plant based on references and coordinates in the plant. The acronym
// originates from the German word "Ortskennzeichnung" (something like "location
// coding system").
type Okz struct {
	// String that provides the location of the plant. This string is built-up by
	// concatenating different information items with separators. Some of these
	// systems are standardized, some others are company-specific.
	LocationIdentifier string `json:"location_identifier" yaml:"location_identifier" mapstructure:"location_identifier"`

	// Type designator that provides support for polymorphism using location.
	LocationType *OkzLocationType `json:"location_type,omitempty" yaml:"location_type,omitempty" mapstructure:"location_type,omitempty"`
}

type OkzLocationType string

const OkzLocationTypeOkz OkzLocationType = "Okz"

var enumValues_OkzLocationType = []interface{}{
	"Okz",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OkzLocationType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OkzLocationType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OkzLocationType, v)
	}
	*j = OkzLocationType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Okz) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["location_identifier"]; raw != nil && !ok {
		return fmt.Errorf("field location_identifier in Okz: required")
	}
	type Plain Okz
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Okz(plain)
	return nil
}

// Operating mode of an asset. Known modes are based on SAT terminology.
// Relevant SAT online documentation:  -
// https://cache.industry.siemens.com/dl/dl-media/801/109801801/att_1079538/v1/SAT_UserGuide_V4_0_SP3_html5_en-US/en-US/index.html#treeId=c79345b269fec83819077e2bbecdf4a4
// -
// https://cache.industry.siemens.com/dl/dl-media/801/109801801/att_1079538/v1/SAT_UserGuide_V4_0_SP3_html5_en-US/en-US/index.html#treeId=2f2825bd45212943f998eee7caeb6fe1
type OperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in OperatingMode: required")
	}
	type Plain OperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = OperatingMode(plain)
	return nil
}

// An organization such as a school, NGO, corporation, club, etc.
type Organization struct {
	// The name of the item.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

// Any offered product or service that might have different versions for the same
// product ID.
type Product struct {
	// The manufacturer of the product.
	Manufacturer interface{} `json:"manufacturer,omitempty" yaml:"manufacturer,omitempty" mapstructure:"manufacturer,omitempty"`

	// The product family represents a group of related products that share common
	// characteristics, design principles, manufacturing processes, or functional
	// purposes, while differing in specific features, sizes, or performance
	// parameters. This attribute establishes the hierarchical classification and
	// inheritance relationship between a specific product instance and its broader
	// product category.
	ProductFamily *string `json:"product_family,omitempty" yaml:"product_family,omitempty" mapstructure:"product_family,omitempty"`

	// The product identifiers, such as ISBN.
	ProductId *string `json:"product_id,omitempty" yaml:"product_id,omitempty" mapstructure:"product_id,omitempty"`

	// Link to identify a product. It can also provide additional information about
	// the product.
	ProductLink *string `json:"product_link,omitempty" yaml:"product_link,omitempty" mapstructure:"product_link,omitempty"`

	// Some products might have different versions under the same product ID. The
	// product version helps differentiating the different versions of a product, if
	// multiple exist.
	ProductVersion *string `json:"product_version,omitempty" yaml:"product_version,omitempty" mapstructure:"product_version,omitempty"`
}

type ProductInstanceInformation struct {
	// A way to identify a product based on the manufacturer and the product
	// identifier given by the manufacturer.
	ManufacturerProduct interface{} `json:"manufacturer_product,omitempty" yaml:"manufacturer_product,omitempty" mapstructure:"manufacturer_product,omitempty"`

	// The serial number or any alphanumeric identifier of a particular product. When
	// attached to an offer, it is a shortcut for the serial number of the product
	// included in the offer.
	SerialNumber *string `json:"serial_number,omitempty" yaml:"serial_number,omitempty" mapstructure:"serial_number,omitempty"`
}

// Program update operation can be performed on the asset
type ProgramUpdateOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProgramUpdateOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in ProgramUpdateOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in ProgramUpdateOperation: required")
	}
	type Plain ProgramUpdateOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ProgramUpdateOperation(plain)
	return nil
}

// Relationship of a ConnectionPoint with another one. This relationship could be
// of the type "ConnectionPoint A relies on the connectivity of ConnectionPoint B
// to work".
type RelatedConnectionPoint struct {
	// Reference to the related ConnectionPoint by providing its identifier.
	ConnectionPointId string `json:"connection_point_id" yaml:"connection_point_id" mapstructure:"connection_point_id"`

	// Type of relationship in an unstructured format.
	CustomRelationship string `json:"custom_relationship" yaml:"custom_relationship" mapstructure:"custom_relationship"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RelatedConnectionPoint) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["connection_point_id"]; raw != nil && !ok {
		return fmt.Errorf("field connection_point_id in RelatedConnectionPoint: required")
	}
	if _, ok := raw["custom_relationship"]; raw != nil && !ok {
		return fmt.Errorf("field custom_relationship in RelatedConnectionPoint: required")
	}
	type Plain RelatedConnectionPoint
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = RelatedConnectionPoint(plain)
	return nil
}

// Reset communication parameter operation can be performed on the asset
type ResetCommunicationParameterOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResetCommunicationParameterOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in ResetCommunicationParameterOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in ResetCommunicationParameterOperation: required")
	}
	type Plain ResetCommunicationParameterOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ResetCommunicationParameterOperation(plain)
	return nil
}

// Restore operation can be performed on the asset
type RestoreOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RestoreOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in RestoreOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in RestoreOperation: required")
	}
	type Plain RestoreOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = RestoreOperation(plain)
	return nil
}

// Asset is running with ODIS.
type RunOdisOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunOdisOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in RunOdisOperatingMode: required")
	}
	type Plain RunOdisOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = RunOdisOperatingMode(plain)
	return nil
}

// Asset is running.
type RunOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in RunOperatingMode: required")
	}
	type Plain RunOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = RunOperatingMode(plain)
	return nil
}

// Asset is running in redundant mode.
type RunRedundantOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunRedundantOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in RunRedundantOperatingMode: required")
	}
	type Plain RunRedundantOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = RunRedundantOperatingMode(plain)
	return nil
}

// Software component representing running software.
// Multiple running software components can be instantiated from a single artifact.
// For example, multiple containers can be instantiated from a single container
// image.
type RunningSoftwareComponent struct {
	// Reference to the software artifact asset.
	// As of now the combination of multiple software artifacts into a running
	// software (for example with plug-ins) is not supported and cannot be natively
	// modeled.
	Artifact interface{} `json:"artifact,omitempty" yaml:"artifact,omitempty" mapstructure:"artifact,omitempty"`

	// Identifier for a running software instance.
	RunningSoftwareId *string `json:"running_software_id,omitempty" yaml:"running_software_id,omitempty" mapstructure:"running_software_id,omitempty"`

	// Type designator that supports polymorphism using software components. This type
	// is used for validation of the provided software components.
	SoftwareComponentType RunningSoftwareComponentSoftwareComponentType `json:"software_component_type" yaml:"software_component_type" mapstructure:"software_component_type"`
}

type RunningSoftwareComponentSoftwareComponentType string

const RunningSoftwareComponentSoftwareComponentTypeRunningSoftwareComponent RunningSoftwareComponentSoftwareComponentType = "RunningSoftwareComponent"

var enumValues_RunningSoftwareComponentSoftwareComponentType = []interface{}{
	"RunningSoftwareComponent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunningSoftwareComponentSoftwareComponentType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RunningSoftwareComponentSoftwareComponentType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RunningSoftwareComponentSoftwareComponentType, v)
	}
	*j = RunningSoftwareComponentSoftwareComponentType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunningSoftwareComponent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["software_component_type"]; raw != nil && !ok {
		return fmt.Errorf("field software_component_type in RunningSoftwareComponent: required")
	}
	type Plain RunningSoftwareComponent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = RunningSoftwareComponent(plain)
	return nil
}

// Any offered product or service. For example: a pair of shoes; a concert ticket;
// the rental of a car; a haircut; or an episode of a TV show streamed online.
type SchemaOrgProduct struct {
	// The manufacturer of the product.
	Manufacturer interface{} `json:"manufacturer,omitempty" yaml:"manufacturer,omitempty" mapstructure:"manufacturer,omitempty"`

	// The product identifiers, such as ISBN.
	ProductId *string `json:"product_id,omitempty" yaml:"product_id,omitempty" mapstructure:"product_id,omitempty"`
}

// Software asset
type SoftwareArtifact struct {
	// An asset identifier is an asset attribute that provides enough information to
	// unequivocally identify the represented object.
	// In some cases the ID attribute acts simultaneously as a reference for the asset
	// instance and as identifier for the represented object. Otherwise at least one
	// asset identifier is needed.
	// There can be multiple asset_identifiers with different goals. For example, the
	// information of a metal nameplate can be used by a human-being to identify a
	// device represented by an asset instance, but a software certificate provided by
	// a device might help a software component identify the device in the network,...
	// An asset identifier might have an identifier_type, that defines its format and
	// possibly even semantics.
	AssetIdentifiers []interface{} `json:"asset_identifiers" yaml:"asset_identifiers" mapstructure:"asset_identifiers"`

	// List of device management operations supported by an asset. Each operation type
	// might appear only once.
	AssetOperations []AssetOperation `json:"asset_operations,omitempty" yaml:"asset_operations,omitempty" mapstructure:"asset_operations,omitempty"`

	// An asset might have a connection point that can be used to connect with the
	// asset. In the case of devices, at least one connection point is required. It
	// might be a connection point needed for AssetManagement for interaction with the
	// asset, or for other connections of the asset related to the asset function but
	// not to device management.
	ConnectionPoints []interface{} `json:"connection_points,omitempty" yaml:"connection_points,omitempty" mapstructure:"connection_points,omitempty"`

	// A textual description of the item's purpose and use.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// URL of the schema that defines the functional object type.
	FunctionalObjectSchemaUrl string `json:"functional_object_schema_url" yaml:"functional_object_schema_url" mapstructure:"functional_object_schema_url"`

	// Type designator that supports polymorphism using functional parts. This type is
	// used for validation of the provided functional objects.
	FunctionalObjectType SoftwareArtifactFunctionalObjectType `json:"functional_object_type" yaml:"functional_object_type" mapstructure:"functional_object_type"`

	// Metadata associated with an object.
	InstanceAnnotations []InstanceAnnotation `json:"instance_annotations,omitempty" yaml:"instance_annotations,omitempty" mapstructure:"instance_annotations,omitempty"`

	// Flag indicating that the software artifact is provided by a hardware
	// manufacturer for one or more of its devices.
	// Unlike other software artifacts, updating the firmware requires contacting the
	// source specified by the device manufacturer.
	// Due to this definition, firmware in IAH has a much wider scope than in some
	// domains, where firmware is only meant to be close-to-the-silicon software.
	IsFirmware *bool `json:"is_firmware,omitempty" yaml:"is_firmware,omitempty" mapstructure:"is_firmware,omitempty"`

	// Possible ways to know where an asset is located.
	Location []interface{} `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// The name of the item.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The current operating mode of the asset.
	OperatingMode interface{} `json:"operating_mode,omitempty" yaml:"operating_mode,omitempty" mapstructure:"operating_mode,omitempty"`

	// Information about the product instance.
	ProductInstanceInformation interface{} `json:"product_instance_information,omitempty" yaml:"product_instance_information,omitempty" mapstructure:"product_instance_information,omitempty"`

	// An asset can host software artifacts that might want to be tracked. This can be
	// used simply to keep track of the firmware version or to keep a full-blown
	// Software Bill of Material (SBOM).
	SoftwareComponents []interface{} `json:"software_components,omitempty" yaml:"software_components,omitempty" mapstructure:"software_components,omitempty"`
}

type SoftwareArtifactComponent struct {
	// Reference to the software artifact asset.
	// As of now the combination of multiple software artifacts into a running
	// software (for example with plug-ins) is not supported and cannot be natively
	// modeled.
	Artifact interface{} `json:"artifact,omitempty" yaml:"artifact,omitempty" mapstructure:"artifact,omitempty"`

	// Type designator that supports polymorphism using software components. This type
	// is used for validation of the provided software components.
	SoftwareComponentType SoftwareArtifactComponentSoftwareComponentType `json:"software_component_type" yaml:"software_component_type" mapstructure:"software_component_type"`
}

type SoftwareArtifactComponentSoftwareComponentType string

const SoftwareArtifactComponentSoftwareComponentTypeSoftwareArtifactComponent SoftwareArtifactComponentSoftwareComponentType = "SoftwareArtifactComponent"

var enumValues_SoftwareArtifactComponentSoftwareComponentType = []interface{}{
	"SoftwareArtifactComponent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SoftwareArtifactComponentSoftwareComponentType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SoftwareArtifactComponentSoftwareComponentType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SoftwareArtifactComponentSoftwareComponentType, v)
	}
	*j = SoftwareArtifactComponentSoftwareComponentType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SoftwareArtifactComponent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["software_component_type"]; raw != nil && !ok {
		return fmt.Errorf("field software_component_type in SoftwareArtifactComponent: required")
	}
	type Plain SoftwareArtifactComponent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SoftwareArtifactComponent(plain)
	return nil
}

type SoftwareArtifactFunctionalObjectType string

const SoftwareArtifactFunctionalObjectTypeSoftwareArtifact SoftwareArtifactFunctionalObjectType = "SoftwareArtifact"

var enumValues_SoftwareArtifactFunctionalObjectType = []interface{}{
	"SoftwareArtifact",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SoftwareArtifactFunctionalObjectType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SoftwareArtifactFunctionalObjectType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SoftwareArtifactFunctionalObjectType, v)
	}
	*j = SoftwareArtifactFunctionalObjectType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SoftwareArtifact) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifiers"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifiers in SoftwareArtifact: required")
	}
	if _, ok := raw["functional_object_schema_url"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_schema_url in SoftwareArtifact: required")
	}
	if _, ok := raw["functional_object_type"]; raw != nil && !ok {
		return fmt.Errorf("field functional_object_type in SoftwareArtifact: required")
	}
	type Plain SoftwareArtifact
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SoftwareArtifact(plain)
	return nil
}

// Identifier especially for software artifacts.
type SoftwareIdentifier struct {
	// Type designator that supports polymorphism using asset identifiers.
	AssetIdentifierType SoftwareIdentifierAssetIdentifierType `json:"asset_identifier_type" yaml:"asset_identifier_type" mapstructure:"asset_identifier_type"`

	// Type of an items identifier.
	IdentifierType *string `json:"identifier_type,omitempty" yaml:"identifier_type,omitempty" mapstructure:"identifier_type,omitempty"`

	// Number that indicates how uncertain an identifier is compared to other
	// identifiers provided by an Asset Link. The higher the number, the more
	// uncertain the identification must be considered. This number must be considered
	// relative to the other identifiers for the same element. The default value is 0,
	// meaning no uncertainty.
	// This index helps to decide which identifiers are better suited for
	// deduplication across Asset Links. The identifier provided by two different
	// Asset Links with the lowest uncertainty should be chosen for deduplication
	// purposes.
	IdentifierUncertainty *int `json:"identifier_uncertainty,omitempty" yaml:"identifier_uncertainty,omitempty" mapstructure:"identifier_uncertainty,omitempty"`

	// The name of the item.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Version of a software artifact.
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type SoftwareIdentifierAssetIdentifierType string

const SoftwareIdentifierAssetIdentifierTypeSoftwareIdentifier SoftwareIdentifierAssetIdentifierType = "SoftwareIdentifier"

var enumValues_SoftwareIdentifierAssetIdentifierType = []interface{}{
	"SoftwareIdentifier",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SoftwareIdentifierAssetIdentifierType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SoftwareIdentifierAssetIdentifierType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SoftwareIdentifierAssetIdentifierType, v)
	}
	*j = SoftwareIdentifierAssetIdentifierType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SoftwareIdentifier) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["asset_identifier_type"]; raw != nil && !ok {
		return fmt.Errorf("field asset_identifier_type in SoftwareIdentifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in SoftwareIdentifier: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in SoftwareIdentifier: required")
	}
	type Plain SoftwareIdentifier
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SoftwareIdentifier(plain)
	return nil
}

// Asset is starting up.
type StartupOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StartupOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in StartupOperatingMode: required")
	}
	type Plain StartupOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StartupOperatingMode(plain)
	return nil
}

// Asset is stopped due to a firmware update.
type StopFwUpdateOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StopFwUpdateOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in StopFwUpdateOperatingMode: required")
	}
	type Plain StopFwUpdateOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StopFwUpdateOperatingMode(plain)
	return nil
}

// Asset is stopped.
type StopOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StopOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in StopOperatingMode: required")
	}
	type Plain StopOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StopOperatingMode(plain)
	return nil
}

// Asset is stopped during self-initialization.
type StopSelfInitializationOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StopSelfInitializationOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in StopSelfInitializationOperatingMode: required")
	}
	type Plain StopSelfInitializationOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StopSelfInitializationOperatingMode(plain)
	return nil
}

// Asset is stopped without ODIS.
type StopWithoutOdisOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StopWithoutOdisOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in StopWithoutOdisOperatingMode: required")
	}
	type Plain StopWithoutOdisOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StopWithoutOdisOperatingMode(plain)
	return nil
}

// Two step firmware update operation can be performed on the asset
type TwoStepFirmwareUpdateOperation struct {
	// Attribute for specifying if the operation is available in terms of true or
	// false
	ActivationFlag bool `json:"activation_flag" yaml:"activation_flag" mapstructure:"activation_flag"`

	// Name of a device management operation.
	OperationName string `json:"operation_name" yaml:"operation_name" mapstructure:"operation_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TwoStepFirmwareUpdateOperation) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["activation_flag"]; raw != nil && !ok {
		return fmt.Errorf("field activation_flag in TwoStepFirmwareUpdateOperation: required")
	}
	if _, ok := raw["operation_name"]; raw != nil && !ok {
		return fmt.Errorf("field operation_name in TwoStepFirmwareUpdateOperation: required")
	}
	type Plain TwoStepFirmwareUpdateOperation
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TwoStepFirmwareUpdateOperation(plain)
	return nil
}

// Asset is performing an update.
type UpdateOperatingMode struct {
	// Name of the operating mode.
	ModeName string `json:"mode_name" yaml:"mode_name" mapstructure:"mode_name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UpdateOperatingMode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode_name"]; raw != nil && !ok {
		return fmt.Errorf("field mode_name in UpdateOperatingMode: required")
	}
	type Plain UpdateOperatingMode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = UpdateOperatingMode(plain)
	return nil
}
