version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directories:
      - "/" # regular config: checks /.github/workflows/
      - "/.github/actions/prepare/"
      - "/cookiecutter-project-template/{{ cookiecutter.al_project }}/.github/workflows/"
      - "/cookiecutter-project-template/{{ cookiecutter.al_project }}/.github/actions/prepare/"
    schedule:
      interval: daily
