# SPDX-FileCopyrightText: 2024 Siemens AG
#
# SPDX-License-Identifier: MIT

include:
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/base.yaml"
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/pre-commit.yaml"
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/clearing.yaml"
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/versioning.yaml" # required for containerization of registry
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "templates/container-image-helper.yaml" # required for containerization of registry

stages:
  - check
  - version
  - lint
  - test
  - build
  - scan
  - release
  - containerize

variables:
  https_proxy: $CODE_PROXY
  http_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY
  HTTP_PROXY: "$CODE_PROXY"
  HTTPS_PROXY: "$CODE_PROXY"
  NO_PROXY: $CODE_NO_PROXY
  GO_BUILD_IMAGE: golang:1.22-alpine
  # Used to hardly enforce that version inside the go.mod file
  GO_MINIMAL_VERSION: 1.20
  CGO_ENABLED: 0
  COOKIECUTTER_PROJECT: cookiecutter-test/
  COOKIECUTTER_PROJECT_NAME: al-test

###########################################################################################################################################
### Shared
###########################################################################################################################################

# sets credentials to access private GO modules located in code.siemens.com
.set_git_https_credentials: &set_git_https_credentials |
  git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@code.siemens.com/".insteadOf https://code.siemens.com/

.set_netrc: &set_netrc |
  echo -e "machine code.siemens.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc

.protoc-go: &protoc-go
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.35.1
  - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

# latest is currently broken, there set the last working version
# https://github.com/omissis/go-jsonschema/issues/131
.go-jsonschema: &go-jsonschema
  - go install github.com/atombender/go-jsonschema/cmd/gojsonschema@v0.12.1

# Place temporary go.mod file, inside cookiecutter  project dir to make go test happy
.cookiecutter_gomod-quirk: &cookiecutter_gomod-quirk ( cd cookiecutter-project-template/*/ && cp ../../go.mod go.mod)

###########################################################################################################################################
### Stage: lint
###########################################################################################################################################

lint:
  image: $GO_BUILD_IMAGE
  stage: lint
  variables:
    GOLANGCILINT_VERSION: "v1.53.3"
  before_script:
    - apk add --no-cache ca-certificates git jq bash curl protobuf-dev
    - echo -e "machine code.siemens.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
    - UPSTREAM_URL=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
    - export BINDIR=/usr/local/bin
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCILINT_VERSION
    - *protoc-go
    - *go-jsonschema
  script:
    - *cookiecutter_gomod-quirk
    - go generate
    #- golangci-lint run --out-format code-climate | tee code-quality-report.json | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'
    - golangci-lint run --issues-exit-code 0 --print-issued-lines=false --out-format code-climate:gl-code-quality-report.json,line-number
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  allow_failure: true

reuse:
  stage: lint
  needs: []
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
  allow_failure: true

###########################################################################################################################################
### Stage: test
###########################################################################################################################################

unit-tests:
  stage: test
  needs: []
  image: $GO_BUILD_IMAGE
  variables:
    CGO_ENABLED: 1
  before_script:
    - go install github.com/jstemmer/go-junit-report/v2@latest
  script:
    - apk add --no-cache git curl gcc libc-dev protobuf-dev
    - *set_git_https_credentials
    - *cookiecutter_gomod-quirk
    - *protoc-go
    - *go-jsonschema
    - go generate
    - go test --race ./... -covermode=atomic -coverprofile=coverage.txt -v 2>&1 | go-junit-report -iocopy -set-exit-code -out report.xml
    - go tool cover -func=coverage.txt
    - go tool cover -html=coverage.txt -o coverage.html
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - coverage.txt
      - coverage.html
    expire_in: 1 day

cookiecutter-setup:
  stage: test
  needs: []
  image: cr.siemens.com/code-ops/poetry-docker:1.8-py3.11
  variables:
    GIT_STRATEGY: clone
  before_script:
    - python -m pip install pipx
    - python -m pipx ensurepath
    - pipx install cookiecutter
    - export PATH="$PATH:/root/.local/bin"
    - cookiecutter --version
  script:
    # Copy pre-defined cookiecutter replay template
    - mkdir -p ~/.cookiecutter_replay/
    - cp ${CI_PROJECT_DIR}/cookiecutter-project-template/cookiecutter-project-template.json ~/.cookiecutter_replay/cookiecutter-project-template.json
    - mkdir ${COOKIECUTTER_PROJECT}
    - cd ${COOKIECUTTER_PROJECT}
    - cookiecutter ${CI_PROJECT_DIR}/cookiecutter-project-template/ --replay
    # directory to the config.yaml used by cookiecutter
    - cd ${COOKIECUTTER_PROJECT_NAME}
    - ls
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG-COOKIECUTTER"
    paths:
      - $COOKIECUTTER_PROJECT/${COOKIECUTTER_PROJECT_NAME}
    policy: pull-push

generate:
  stage: test
  needs: []
  image: $GO_BUILD_IMAGE
  variables:
    CGO_ENABLED: 1
  script:
    - apk add --no-cache git curl gcc libc-dev protobuf-dev
    - *set_git_https_credentials
    - *cookiecutter_gomod-quirk
    - *protoc-go
    - *go-jsonschema
    - go generate
    - git diff --exit-code -w -G'(^[^\*# /])|(^#\w)|(^\s+[^\*#/])'
  allow_failure: true

#TODO: Find a way to upload scan report to Gitlab or Github
vulncheck:
  stage: test
  needs: []
  image: $GO_BUILD_IMAGE
  before_script:
    - go install golang.org/x/vuln/cmd/govulncheck@latest
  script:
    - go version
    - govulncheck -show color ./...
  allow_failure: true

###########################################################################################################################################
### Stage: build
###########################################################################################################################################

.go-build:
  stage: build
  image: archlinux:latest
  variables:
    GONOSUMDB: code.siemens.com
    GOPRIVATE: code.siemens.com
  before_script:
    - pacman -Sy --noconfirm
    - pacman -S --noconfirm go zig goreleaser git protobuf
    - *protoc-go
    - *go-jsonschema

# Vendors the needed Go packages. This vendor/ is used, inside the
# release job, to include the vendor/ directory, into
# the generated cdm-dcd-sdk archive. This also, updates the go.mod file w/
# the most recent tag of the cdm-dcd-sdk
# Caution: this removes the cookiecutter specific header of the go.mod file.
#          This header has to be restored inside the create-release job, to have
#          and full working released archive.
cookiecutter-vendor:
  extends: .go-build
  variables:
    GIT_STRATEGY: clone
  script:
    - *set_netrc
    - cd ${COOKIECUTTER_PROJECT}/${COOKIECUTTER_PROJECT_NAME}/
    - cp go.mod.tmpl go.mod
    - >
      if [ -z $CI_COMMIT_TAG ]; then
        echo "detected non-tag build"
        go get ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/v2@${CI_COMMIT_SHA}
      else
        go get ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/v2@${CI_COMMIT_TAG}
      fi
    # Prepare
    - cat go.mod
    - go generate ./...

    # See https://go.dev/blog/toolchain for references
    - go mod edit -go=$GO_MINIMAL_VERSION
    # Since, we still want to support go1.20, we remove the toolchain
    # Enable it from 1.21 on.
    - go mod edit -toolchain=none

    - go mod tidy
    - go mod download

    # Doing the step twice, since go mod tidy re-enables
    - go mod edit -toolchain=none

    # We include the SDK inside a local folder, for now!
    - git clone ${CI_PROJECT_URL}
    - >
      if [ -z $CI_COMMIT_TAG ]; then
        echo "detected non-tag build"
        cd ${CI_PROJECT_NAME} && git checkout ${CI_COMMIT_SHA} && cd ..
      else
        cd ${CI_PROJECT_NAME} && git checkout ${CI_COMMIT_TAG} && cd ..
      fi
    - go mod edit -replace=${CI_SERVER_HOST}/${CI_PROJECT_PATH}/v2=./${CI_PROJECT_NAME}
    - cat go.mod
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG-COOKIECUTTER"
    paths:
      - $COOKIECUTTER_PROJECT
    policy: pull-push

# Builds the already bootstrapped Asset Link
# and uses the vendored files.
go:version:matrix:
  stage: build
  variables:
    GIT_STRATEGY: clone
    GONOSUMDB: code.siemens.com
    GOPRIVATE: code.siemens.com
  image: golang:$VERSION
  needs: ["cookiecutter-vendor"]
  before_script:
    - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
    - apt-get update -qq
    - apt-get install --assume-yes --no-install-recommends  git goreleaser
  script:
    - cd ${COOKIECUTTER_PROJECT}/${COOKIECUTTER_PROJECT_NAME}/
    - go version
    - goreleaser build --snapshot --clean --single-target
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG-COOKIECUTTER"
    paths:
      - $COOKIECUTTER_PROJECT
    policy: pull
  parallel:
    matrix:
      - VERSION: ["1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "latest"]
  allow_failure: true

build:
  extends: .go-build
  script:
    - *set_netrc
    - goreleaser build --snapshot --clean --single-target
  artifacts:
    expire_in: 1 day
    paths: [dist]

###########################################################################################################################################
### Stage: scan
### BlackDuck upload for SVM
###########################################################################################################################################

.rulesBlackDuckUpload:
  - &MAIN_TAG
    if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG
    when: always
    allow_failure: true # should not happen, but should not block something like a critical bug fix
  - &BRANCH
    if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: manual
    allow_failure: true

analyzePackageDependencies:
  extends: .analyze_package_dependencies_go
  rules:
    - *MAIN_TAG
    - *BRANCH
  needs: ["build"]

clearingSubmit:
  needs: ["analyzePackageDependencies"]
  extends: .clearing_submit
  rules:
    - *MAIN_TAG
    - *BRANCH

###########################################################################################################################################
### Stage: release
###########################################################################################################################################

create-release:
  stage: release
  image: archlinux:latest
  # Disable artifact passing
  dependencies: []
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags
    GIT_DEPTH: 0
  before_script:
    - pacman -Sy --noconfirm
    - pacman -S --noconfirm go zig goreleaser git git-lfs protobuf
    - git lfs install
    - *protoc-go
    - *go-jsonschema
  script:
    - *set_netrc
    # Copy go.mod and the vendor dir for the SDK archive into the cookiecutter template
    # the go.mod inside the cookiecutter-project-template does not have to contain the cdm-dcd-sdk.
    # It is updated inside the cookiecutter-vendor job.
    - ls
    - ls cookiecutter-project-template/
    - cp -a ${COOKIECUTTER_PROJECT}/${COOKIECUTTER_PROJECT_NAME}/go.mod cookiecutter-project-template/\{\{\ cookiecutter.al_id\ \}\}/
    # Replace first line inside go.mod, due to it's specific from the cookiecutter template
    - sed -i "1s/.*/module {{cookiecutter.al_id}}/" cookiecutter-project-template/\{\{\ cookiecutter.al_id\ \}\}/go.mod
    - cp -a ${COOKIECUTTER_PROJECT}/${COOKIECUTTER_PROJECT_NAME}/${CI_PROJECT_NAME}/ cookiecutter-project-template/\{\{\ cookiecutter.al_id\ \}\}/
    # Create release
    - |
      if [ "${CI_COMMIT_TAG:-}" != "" ]; then
          export GITLAB_TOKEN="$GITLAB_RELEASE_TOKEN"
          echo "*** Creating official release ***"
          goreleaser release --clean
      else
          echo "*** Creating dry-run release ***"
          goreleaser release --clean --snapshot
      fi
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  cache:
    key: "$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG-COOKIECUTTER"
    paths:
      - $COOKIECUTTER_PROJECT
    policy: pull

###########################################################################################################################################
### Stage: containerize
###########################################################################################################################################

.container_registry_login: &container_registry_login |
  echo "{\"auths\":{\"$CODE_CR_PROXY\":{\"username\":\"$GITLAB_USER_LOGIN\",\"password\":\"$CR_PROXY_TOKEN\"}}}" > /kaniko/.docker/config.json

.build_tag_push_containerimage:
  stage: containerize
  variables:
    COMPONENT_CONTEXT: ""
    COMPONENT_NAME: "registry"
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug@sha256:c3109d5926a997b100c4343944e06c6b30a6804b2f9abe0994d3de6ef92b028e
    entrypoint: [""]
  # Let GitLab inject a CI JWT token into the build
  id_tokens:
    CR_PROXY_TOKEN:
      aud: https://code.siemens.com
  script:
    - *container_registry_login
    - CONTEXT=$CI_PROJECT_DIR/$COMPONENT_CONTEXT
    - IMAGE_STORAGE_URL=$CI_REGISTRY_IMAGE/$COMPONENT_NAME:$IMAGE_TAG
    - printf "IMAGE_STORAGE_URL=$IMAGE_STORAGE_URL\n" >> build.env
    - >
      /kaniko/executor \
        --build-arg http_proxy="$http_proxy" \
        --build-arg https_proxy="$https_proxy" \
        --build-arg no_proxy="$no_proxy" \
        --build-arg COMPONENT_NAME="$COMPONENT_NAME" \
        --context $CONTEXT \
        --dockerfile $CONTEXT/Dockerfile \
        --destination $IMAGE_STORAGE_URL \
        --registry-mirror $CODE_CR_PROXY_HOST
  retry: 1
  artifacts:
    reports:
      dotenv: build.env

.build_tag_push_containerimage_multiarch:
  extends: .build_tag_push_containerimage
  variables:
    ARCH: "amd64"
  # Let GitLab inject a CI JWT token into the build
  id_tokens:
    CR_PROXY_TOKEN:
      aud: https://code.siemens.com
  script:
    - *container_registry_login
    - CONTEXT=$CI_PROJECT_DIR/$COMPONENT_CONTEXT
    - IMAGE_STORAGE_URL_BASE=$CI_REGISTRY_IMAGE/$COMPONENT_NAME:$IMAGE_TAG
    - printf "IMAGE_STORAGE_URL_BASE=$IMAGE_STORAGE_URL_BASE\n" >> build.env
    - IMAGE_STORAGE_URL=$IMAGE_STORAGE_URL_BASE-$ARCH
    - printf "IMAGE_STORAGE_URL=$IMAGE_STORAGE_URL\n" >> build.env
    - |
      case $ARCH in
          amd64)
            ;;
          arm64)
            ;;
          *)
            echo "Unsupported architecture: $ARCH"
            exit 1
            ;;
      esac
    - >
      /kaniko/executor \
        --build-arg http_proxy="$http_proxy" \
        --build-arg https_proxy="$https_proxy" \
        --build-arg no_proxy="$no_proxy" \
        --build-arg COMPONENT_NAME="$COMPONENT_NAME" \
        --build-arg TARGETARCH="$ARCH" \
        --context $CONTEXT \
        --dockerfile $CONTEXT/Dockerfile \
        --destination $IMAGE_STORAGE_URL \
        --registry-mirror $CODE_CR_PROXY_HOST

createRegistryImageAmd64:
  extends: .build_tag_push_containerimage_multiarch
  variables:
    COMPONENT_CONTEXT: "registry/"
    COMPONENT_NAME: "registry"
    ARCH: "amd64"

createRegistryImageArm64:
  extends: .build_tag_push_containerimage_multiarch
  variables:
    COMPONENT_CONTEXT: "registry/"
    COMPONENT_NAME: "registry"
    ARCH: "arm64"
  tags:
    - DOCKER-AARCH64

createRegistryContainerImageIndex:
  extends: .createContainerImageIndex
  stage: containerize
  needs:
    - version
    - createRegistryImageAmd64
    - createRegistryImageArm64
