title: Asset Link SDK
description: Documentation for the Asset Link SDK
theme: just-the-docs

nav_order: 1
search_enabled: true
favicon_ico: "/images/favicon.ico"

nav:
  - title: "📜 Documentation"
    url: /
  - title: "📖 Overview"
    url: /overview
  - title: "🚀 Bootstrapping your own Asset Link"
    url: /bootstrap
  - title: "🛠️ Command Line Tool"
    url: /cmd
  - title: "📊 Observability Webserver"
    url: /observability

include:
  - index.md
  - overview.md
  - bootstrap.md
  - cmd.md
  - observability.md
