title: Asset Link SDK
description: Documentation for the Asset Link SDK
source: docs

remote_theme: just-the-docs/just-the-docs

nav_sort: case_insensitive
search_enabled: true

color_scheme: dark
favicon_ico: "/docs/images/favicon.ico"

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_order: 1
  nav_order: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

plugins:
  - jekyll-remote-theme
