# SPDX-FileCopyrightText: 2026 Siemens AG
#
# SPDX-License-Identifier: MIT

FROM scratch

ARG TARGETOS
ARG TARGETARCH

COPY --chmod=0755 cdm-al-reference-${TARGETOS}-${TARGETARCH} /al

ENTRYPOINT ["/al"]
