# SPDX-FileCopyrightText: {{cookiecutter.year}} {{cookiecutter.company}}
#
# SPDX-License-Identifier: {{cookiecutter.license}}

FROM scratch

COPY --chmod=0755 {{ cookiecutter.al_project }} /al

ENTRYPOINT ["/al"]
