# SPDX-FileCopyrightText: 2024 Siemens AG
#
# SPDX-License-Identifier: MIT

name: Prepare Environment
description: Setup Go and install dependencies

inputs:
  go-version:
    description: 'Desired Go version'
    required: false
    default: 'stable'

# outputs:

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
    - name: Install Dependencies
      shell: bash
      run: |
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.35.1
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
        go install github.com/atombender/go-jsonschema/cmd/gojsonschema@v0.12.1
